# GitHub Action for BaapUI repository
# Automatically invalidates BaapMCP cache when components or metadata change

name: Invalidate MCP Cache

on:
  push:
    branches: [main]
    paths:
      - 'components-metadata.json'
      - 'src/components/**'
      - 'package.json'
  workflow_dispatch: # Allow manual trigger

jobs:
  invalidate-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Invalidate BaapMCP Cache
        run: |
          curl -X POST https://mcp.baapui.com/invalidate-cache \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CACHE_INVALIDATION_KEY }}" \
            -d '{"source": "github-action", "trigger": "metadata-update", "commit": "${{ github.sha }}"}' \
            || echo "Cache invalidation failed (non-critical)"
      
      - name: Log cache invalidation
        run: echo "✅ BaapMCP cache invalidation triggered"

# Alternative: Add this as a step to your existing build/deploy workflow
# 
# - name: Invalidate MCP Cache
#   if: success() # Only if build was successful
#   run: |
#     curl -X POST https://mcp.baapui.com/invalidate-cache \
#       -H "Content-Type: application/json" \
#       -H "Authorization: Bearer ${{ secrets.CACHE_INVALIDATION_KEY }}" \
#       -d '{"source": "github-action", "repository": "${{ github.repository }}", "commit": "${{ github.sha }}"}' \
#       || echo "Cache invalidation failed (non-critical)" 